In [20]:
%matplotlib inline

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
data = pd.read_csv('data/second_exp_26_09_17/full_data.csv')

In [24]:
eye_t = data[data.device=='eye+template']
eye_d = data[data.device=='eye+dirui']
real = data[data.device=='sysmex']

In [25]:
indicators = real.columns[1:11]

# 1. Совпадение между показаниями глаза на различных шкалах

### hard-точность для различных индикаторов 

In [26]:
print indicators.values
print np.mean(eye_t[indicators].values == eye_d[indicators].values,axis=0)

['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.8  0.9  1.   1.   0.5  1.   0.9  0.9  0.6  0.6]


In [27]:
print "Усредненная hard-точность"
print np.mean(eye_t[indicators].values == eye_d[indicators].values)

Усредненная hard-точность
0.82


### soft-точность

In [28]:
print "soft-точность для различных индикаторов"
print indicators.values
print np.mean(np.abs(eye_t[indicators].values - eye_d[indicators].values)<=1,axis=0)

soft-точность для различных индикаторов
['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 1.   1.   1.   1.   0.9  1.   1.   1.   1.   0.9]


In [29]:
print "усредненная soft-точность"
print np.mean(np.abs(eye_t[indicators].values - eye_d[indicators].values)<=1)

усредненная soft-точность
0.98


# Совпадение между глазом и эталонными показаниями

## Eye+template vs Sysmex

In [58]:
ref = real.iloc[:-1]

In [59]:
print indicators.values
print np.mean(eye_t[indicators].values == ref[indicators].values,axis=0)

['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.6  0.   0.7  0.4  0.6  1.   0.6  1.   0.3  0.2]


In [60]:
print "Усредненная hard-точность"
print np.mean(eye_t[indicators].values == ref[indicators].values)

Усредненная hard-точность
0.54


In [61]:
print "soft-точность для различных индикаторов"
print indicators.values
print np.mean(np.abs(eye_t[indicators].values - ref[indicators].values)<=1,axis=0)

soft-точность для различных индикаторов
['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.9  0.9  1.   0.6  0.9  1.   0.7  1.   0.8  0.7]


In [62]:
print "усредненная soft-точность"
print np.mean(np.abs(eye_t[indicators].values - ref[indicators].values)<=1)

усредненная soft-точность
0.85


## Eye+dirui palette vs Sysmex

In [63]:
print "hard-точность для различных индикаторов"
print indicators.values
print np.mean(eye_d[indicators].values == ref[indicators].values,axis=0)

hard-точность для различных индикаторов
['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.7  0.1  0.7  0.4  0.7  1.   0.6  0.9  0.   0.4]


In [67]:
def hard_accuracy(x,y,indicators=indicators):
    try:
        print indicators.values
        accs = np.mean(x[indicators].values==y[indicators].values,axis=0)
        print accs.round(2)
        return accs
    except:
        print "Something bad happened"
        
def soft_accuracy(x,y,indicators=indicators):
    try:
        print indicators.values
        accs = np.mean(np.abs(x[indicators].values-y[indicators].values)<=1,axis=0)
        print accs.round(2)
        return accs
    except:
        print "Something bad happened"

In [66]:
print "Усредненная hard-точность"
print np.mean(eye_d[indicators].values == ref[indicators].values)

Усредненная hard-точность
0.55


In [39]:
print "soft-точность для различных индикаторов"
print indicators.values
print np.mean(np.abs(eye_d[indicators].values - ref[indicators].values)<=1,axis=0)

soft-точность для различных индикаторов
['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 1.   0.9  1.   0.6  0.8  1.   0.7  1.   0.7  0.8]


In [40]:
print "усредненная soft-точность"
print np.mean(np.abs(eye_d[indicators].values - ref[indicators].values)<=1)

усредненная soft-точность
0.85


# Анализируем показания прибора и алгоритма

In [41]:
phone_m15 = data[(data.template == 'template-15')&(data.light=='light')]

In [42]:
real = data[data.device == 'sysmex']

In [43]:
from itertools import combinations

In [44]:
templates = ['template', 'template-15', 'template+15']
lights = ['no_light','light']

In [45]:
for t in templates:
    for l in lights:
        p = data[(data.template == t)&(data.light==l)&(data.ID!='empty')]
        
        print t,l
        print "size of ",len(p)
        print 'Hard',np.mean(hard_accuracy(real.loc[real.ID.isin(p.ID.values)],p))
        print 'Soft',np.mean(soft_accuracy(real.loc[real.ID.isin(p.ID.values)],p))
        print '++++++++++++++++\n'

template no_light
size of  7
Hard ['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.86  1.    1.    0.43  0.43  0.57  0.43  0.71  0.29  0.14]
0.585714285714
Soft ['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.86  1.    1.    0.57  1.    0.71  0.71  0.71  1.    0.29]
0.785714285714
++++++++++++++++

template light
size of  8
Hard ['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.75  0.88  0.88  0.12  0.5   0.75  0.5   0.75  0.25  0.12]
0.55
Soft ['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.75  1.    1.    0.38  1.    0.75  0.75  0.75  0.88  0.62]
0.7875
++++++++++++++++

template-15 no_light
size of  8
Hard ['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.75  0.75  0.75  0.25  0.25  0.75  0.5   0.5   0.38  0.  ]
0.4875
Soft ['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.75  0.75  0.75  0.25  0.88  0.75  0.62  0.5   0.62  0.62]
0.65
++++++++++++++++

template-15 light
size of  10
Hard ['URO' '

In [46]:
eye_d = data[data.device == 'eye+dirui']

In [47]:
hard_accuracy(real,phone_m15)

['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.64  0.82  0.91  0.09  0.18  0.64  0.73  0.82  0.18  0.36]


array([ 0.63636364,  0.81818182,  0.90909091,  0.09090909,  0.18181818,
        0.63636364,  0.72727273,  0.81818182,  0.18181818,  0.36363636])

In [49]:
print 'Soft acc'
np.mean(soft_accuracy(real,phone_m15))

Soft acc
['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.73  0.82  1.    0.27  0.82  0.73  0.73  0.82  0.55  0.45]


0.69090909090909092

In [50]:
phone = data[(data.template == 'template')&(data.light=='light')]

In [51]:
np.mean(soft_accuracy(real.loc[real.ID.isin(phone.ID.values)],phone))

['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.75  1.    1.    0.38  1.    0.75  0.75  0.75  0.88  0.62]


0.78749999999999998

In [52]:
hard_accuracy(real.loc[real.ID.isin(phone.ID.values)],phone)

['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.75  0.88  0.88  0.12  0.5   0.75  0.5   0.75  0.25  0.12]


array([ 0.75 ,  0.875,  0.875,  0.125,  0.5  ,  0.75 ,  0.5  ,  0.75 ,
        0.25 ,  0.125])

In [53]:
np.mean(soft_accuracy(eye_d,phone_m15.loc[phone_m15.ID.isin(eye_d.ID.values)]))

['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.9  0.9  0.8  0.1  0.6  0.8  0.9  0.6  0.5  0.5]


0.65999999999999992

In [54]:
hard_accuracy(eye_d,phone_m15.loc[phone_m15.ID.isin(eye_d.ID.values)])

['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.6  0.1  0.6  0.   0.3  0.7  0.8  0.6  0.4  0.1]


array([ 0.6,  0.1,  0.6,  0. ,  0.3,  0.7,  0.8,  0.6,  0.4,  0.1])

In [55]:
np.mean(soft_accuracy(eye_d,phone_m15.loc[phone_m15.ID.isin(eye_d.ID.values)]))

['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.9  0.9  0.8  0.1  0.6  0.8  0.9  0.6  0.5  0.5]


0.65999999999999992

In [56]:
for t in ['template-15','template','template+15']:
    print len(data[(data.light=='no_light')&(data.template==t)])

9
8
7


In [57]:
phone_m15_nolight = data[(data.light=='no_light')&(data.template==t)]

In [69]:
np.mean(soft_accuracy(phone_m15_nolight,real.loc[real.ID.isin(phone_m15_nolight.ID.values)]))

['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.71  1.    1.    0.86  1.    1.    0.86  0.86  0.86  0.71]


0.88571428571428579

In [73]:
phone_nolight = data[(data.light=='no_light')&(data.template=='template')].iloc[:-1]

In [77]:
np.mean(soft_accuracy(phone_nolight,real.loc[real.ID.isin(phone_nolight.ID.values)]))

['URO' 'BIL' 'KET' 'BLO' 'PRO' 'NIT' 'LEU' 'GLU' 'SG' 'PH']
[ 0.86  1.    1.    0.86  1.    1.    0.71  1.    0.86  0.86]


0.91428571428571437